server:
  port: 9002 #端口
spring:
  favicon:
    enabled: false
  application:
    name: service-order #服务名称
#配置eureka server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    #注册到两个eureka上
      defaultZone: http://localhost:9005/eureka/,http://localhost:9006/eureka/
  instance:
    prefer-ip-address: true #使用ip地址进行注册