server:
  port: 9005 #端口
spring:
  application:
    name: service-register #服务名称
# 配置eureka server
eureka:
  client:
    service-url: #将自己注册到9006对就的注册中心上
      defaultZone: http://127.0.0.1:9006/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
