server:
  port: 9001 #端口
spring:
  favicon:
    enabled: false
  application:
    name: service-product #服务名称
  datasource:
    username: root
    password: China123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  #配置eureka server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
    #注册到两个eureka上
      defaultZone: http://localhost:9005/eureka/,http://localhost:9006/eureka/
  instance:
    prefer-ip-address: true #使用ip地址进行注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 向注册中心中注册服务id
    lease-renewal-interval-in-seconds: 5 #每5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10秒内没有心跳，则踢除服务
